export const DESIGN_SYSTEM_VERSION = '1.0.1'
export const DESIGN_SYSTEM_RELEASE_DATE = '2026-07-10'
export const DESIGN_SYSTEM_SCHEMA_VERSION = 1

const component = ({
  name,
  category,
  purpose,
  useWhen,
  avoid,
  variants = ['default'],
  states = ['default'],
  accessibility,
  responsive,
  example,
}) => ({
  name,
  category,
  purpose,
  useWhen,
  avoid,
  variants,
  states,
  accessibility,
  responsive,
  example,
})

export const COMPONENT_MANIFEST = [
  component({
    name: 'Button',
    category: 'action',
    purpose: 'Runs a labeled user action with stable touch geometry.',
    useWhen: 'Use for primary, secondary, ghost, strong, or destructive actions.',
    avoid: 'Do not use for navigation or icon-only actions.',
    variants: ['primary', 'strong', 'secondary', 'ghost', 'danger', 'align:center', 'align:start', 'align:between'],
    states: ['default', 'hover', 'focus-visible', 'disabled', 'loading'],
    accessibility: 'Use concrete visible text; loading disables the action and exposes aria-busy.',
    responsive: 'Sizes use density-aware control tokens; fullWidth is appropriate on narrow sheets and forms. Use start or between alignment for full-width list and sidebar rows.',
    example: '<Button variant="primary" align="start" fullWidth loading={saving}>Save changes</Button>',
  }),
  component({
    name: 'IconButton',
    category: 'action',
    purpose: 'Runs a compact action represented by one familiar icon.',
    useWhen: 'Use for close, previous, next, refresh, and similarly established icon actions.',
    avoid: 'Do not use without an aria-label or when the action needs explanatory text.',
    variants: ['primary', 'strong', 'secondary', 'ghost', 'danger'],
    states: ['default', 'hover', 'focus-visible', 'disabled'],
    accessibility: 'aria-label is required; the icon is supplementary.',
    responsive: 'Square targets remain density-aware and meet touch minimums.',
    example: '<IconButton icon={<X />} aria-label="Close" onClick={onClose} />',
  }),
  component({
    name: 'Card',
    category: 'surface',
    purpose: 'Groups related content on a semantic elevated surface.',
    useWhen: 'Use for bounded content groups, summaries, and tappable list cards.',
    avoid: 'Do not wrap every section in a card or use interactive mode without an action.',
    variants: ['surface', 'subtle', 'accent', 'interactive'],
    states: ['default', 'hover', 'focus-visible'],
    accessibility: 'Interactive cards provide keyboard activation; use a native link when the card only navigates.',
    responsive: 'Padding follows shared density and card-spacing tokens.',
    example: '<Card tone="subtle" padding="sm">Household summary</Card>',
  }),
  component({
    name: 'Chip',
    category: 'data-display',
    purpose: 'Shows compact status, metadata, filters, or lightweight actions.',
    useWhen: 'Use static chips for labels and interactive chips for filters or compact actions.',
    avoid: 'Do not use as a substitute for primary buttons or segmented view selection.',
    variants: ['neutral', 'accent', 'success', 'info', 'warning', 'danger'],
    states: ['default', 'selected', 'focus-visible', 'disabled'],
    accessibility: 'Interactive chips render as buttons and need clear labels; never communicate status by color alone.',
    responsive: 'Small and medium sizes use density-aware minimum heights.',
    example: '<Chip tone="success">Synced</Chip>',
  }),
  component({
    name: 'CalendarPill',
    category: 'data-display',
    purpose: 'Displays dense read-only calendar metadata with consistent geometry.',
    useWhen: 'Use for time, owner, category, and other compact calendar facts.',
    avoid: 'Do not use for actions or editable selection.',
    variants: ['default'],
    states: ['default'],
    accessibility: 'Include readable text and do not rely on color alone.',
    responsive: 'Keeps the established dense calendar scale across densities.',
    example: '<CalendarPill icon={<Clock />}>3:30 PM</CalendarPill>',
  }),
  component({
    name: 'SegmentedControl',
    category: 'selection',
    purpose: 'Selects exactly one labeled view or mode from a small set.',
    useWhen: 'Use for two to four mutually exclusive, frequently switched options.',
    avoid: 'Do not use for independent toggles, long lists, or navigation between routes.',
    variants: ['default', 'fullWidth'],
    states: ['default', 'selected', 'dragging', 'focus-visible', 'disabled'],
    accessibility: 'Exposes a labeled radiogroup-style choice and preserves keyboard activation.',
    responsive: 'Can fill narrow containers; the thumb and items retain density-aware targets.',
    example: '<SegmentedControl aria-label="Calendar view" value={view} onChange={setView} options={views} />',
  }),
  component({
    name: 'Field',
    category: 'form',
    purpose: 'Wires a form label, hint, error, and control into one accessible field.',
    useWhen: 'Wrap Input, Select, or Textarea whenever the control needs a visible label.',
    avoid: 'Do not use placeholder text as the only label.',
    variants: ['default', 'error'],
    states: ['default', 'invalid', 'disabled'],
    accessibility: 'Automatically connects label, hint, and error IDs to its child control.',
    responsive: 'Fills its container and composes with responsive form grids.',
    example: '<Field label="Home address" error={error}><Input value={address} /></Field>',
  }),
  component({
    name: 'Input',
    category: 'form',
    purpose: 'Captures a single line of text or native input data.',
    useWhen: 'Use inside Field for short freeform values.',
    avoid: 'Do not use for long prose, stable option lists, or custom button-like controls.',
    variants: ['default', 'invalid'],
    states: ['default', 'focus-visible', 'invalid', 'disabled'],
    accessibility: 'Use with Field or provide an explicit accessible name.',
    responsive: 'Uses full width and density-aware control height.',
    example: '<Field label="Name"><Input value={name} onChange={onChange} /></Field>',
  }),
  component({
    name: 'Select',
    category: 'form',
    purpose: 'Chooses one value from a short stable native option list.',
    useWhen: 'Use when all options are known and search is unnecessary.',
    avoid: 'Do not use for searchable or very long lists; use Combobox instead.',
    variants: ['default', 'invalid'],
    states: ['default', 'focus-visible', 'invalid', 'disabled'],
    accessibility: 'Retains native select semantics and should be paired with Field.',
    responsive: 'Uses full width and density-aware control height.',
    example: '<Field label="Theme"><Select value={theme}><option value="day">Day</option></Select></Field>',
  }),
  component({
    name: 'Textarea',
    category: 'form',
    purpose: 'Captures multi-line freeform text.',
    useWhen: 'Use for notes, descriptions, and instructions.',
    avoid: 'Do not use for single values or structured selections.',
    variants: ['default', 'invalid'],
    states: ['default', 'focus-visible', 'invalid', 'disabled'],
    accessibility: 'Pair with Field and provide meaningful errors or hints.',
    responsive: 'Uses full width while rows control its initial height.',
    example: '<Field label="Notes"><Textarea rows={4} value={notes} /></Field>',
  }),
  component({
    name: 'Modal',
    category: 'overlay',
    purpose: 'Presents a focused centered dialog without changing page geometry.',
    useWhen: 'Use for short focused workflows, decisions, and confirmations.',
    avoid: 'Do not nest overlays or use for long mobile-first workflows better suited to Sheet.',
    variants: ['sm', 'md', 'lg'],
    states: ['closed', 'opening', 'open', 'closing'],
    accessibility: 'Owns dialog semantics, focus trapping, Escape handling, scroll lock, and focus return.',
    responsive: 'Fits the viewport with safe outer padding and bounded sizes.',
    example: '<Modal open={open} onClose={onClose} title="Edit item">...</Modal>',
  }),
  component({
    name: 'Sheet',
    category: 'overlay',
    purpose: 'Presents an edge-anchored drawer for longer or contextual workflows.',
    useWhen: 'Use bottom sheets on touch surfaces and right drawers for contextual desktop tasks.',
    avoid: 'Do not double-wrap with a backdrop or independent focus trap.',
    variants: ['bottom', 'right'],
    states: ['closed', 'opening', 'open', 'closing'],
    accessibility: 'Owns dialog semantics, focus trapping, Escape handling, scroll lock, and focus return.',
    responsive: 'Bottom sheets suit phone/kiosk; right sheets suit wider contextual workflows.',
    example: '<Sheet open={open} onClose={onClose} title="Earlier today" showHandle>...</Sheet>',
  }),
  component({
    name: 'PageShell',
    category: 'layout',
    purpose: 'Applies canonical page width, gutters, section rhythm, and optional header.',
    useWhen: 'Use as the outer composition for standard routed pages.',
    avoid: 'Do not use inside edge-to-edge tools that already own scrolling and gutters.',
    variants: ['narrow', 'default', 'wide', 'full'],
    states: ['default'],
    accessibility: 'Keeps heading and action content in a predictable semantic order.',
    responsive: 'Gutters and measures follow phone, tablet, desktop, and kiosk tokens.',
    example: '<PageShell title="Saved places" width="narrow">...</PageShell>',
  }),
  component({
    name: 'Heading',
    category: 'typography',
    purpose: 'Renders semantic display and heading typography roles.',
    useWhen: 'Use for page titles, section titles, and editorial display text.',
    avoid: 'Do not apply arbitrary font-size utilities or choose a role only for visual size.',
    variants: ['display-xl', 'display-lg', 'display-md', 'display-sm', 'heading'],
    states: ['default'],
    accessibility: 'Choose the semantic element separately when document hierarchy requires it.',
    responsive: 'Each role scales through compact, touch, and kiosk density tokens.',
    example: '<Heading role="display-sm" as="h1">Calendar</Heading>',
  }),
  component({
    name: 'Text',
    category: 'typography',
    purpose: 'Renders semantic body, supporting, and caption text roles.',
    useWhen: 'Use for prose, helper copy, metadata, and captions.',
    avoid: 'Do not introduce arbitrary sizes or use muted text for essential instructions.',
    variants: ['body-lg', 'body', 'body-sm', 'caption'],
    states: ['default', 'muted'],
    accessibility: 'Use an appropriate semantic element and maintain readable contrast.',
    responsive: 'Supporting roles remain distance-readable in compact, touch, and kiosk densities.',
    example: '<Text role="body-sm" muted>Last synced 2 minutes ago</Text>',
  }),
  component({
    name: 'Switch',
    category: 'selection',
    purpose: 'Changes one binary setting immediately.',
    useWhen: 'Use for independent on/off preferences.',
    avoid: 'Do not use for multi-option choices, confirmation-required actions, or form submission.',
    variants: ['default'],
    states: ['off', 'on', 'focus-visible', 'disabled'],
    accessibility: 'Exposes role=switch, checked state, visible label, and optional description.',
    responsive: 'Row and control targets remain touch-safe across densities.',
    example: '<Switch label="Conversation mode" checked={enabled} onCheckedChange={setEnabled} />',
  }),
  component({
    name: 'Checkbox',
    category: 'selection',
    purpose: 'Selects an independent item in a set.',
    useWhen: 'Use for zero-or-more selection or acknowledgment.',
    avoid: 'Do not use for immediate settings or one-of-many choices.',
    variants: ['default'],
    states: ['unchecked', 'checked', 'indeterminate', 'focus-visible', 'disabled'],
    accessibility: 'Uses a native checkbox with visible label and optional description.',
    responsive: 'The complete labeled row provides a stable touch target.',
    example: '<Checkbox label="Include pantry staples" checked={checked} onChange={onChange} />',
  }),
  component({
    name: 'Radio',
    category: 'selection',
    purpose: 'Selects exactly one item from a related group.',
    useWhen: 'Use when all one-of-many choices should remain visible.',
    avoid: 'Do not use for independent choices or route navigation.',
    variants: ['default'],
    states: ['unchecked', 'checked', 'focus-visible', 'disabled'],
    accessibility: 'Uses native radio semantics; share a name across the group and include visible labels.',
    responsive: 'The complete labeled row provides a stable touch target.',
    example: '<Radio name="delivery" value="pickup" label="Pickup" checked={mode === "pickup"} />',
  }),
  component({
    name: 'Combobox',
    category: 'form',
    purpose: 'Searches and selects from a longer option list.',
    useWhen: 'Use when a Select list would be too long or needs filtering.',
    avoid: 'Do not use for a short stable list or unrestricted freeform text.',
    variants: ['default'],
    states: ['closed', 'open', 'filtered', 'empty', 'focus-visible', 'disabled'],
    accessibility: 'Wires combobox, listbox, active option, keyboard navigation, and visible label semantics.',
    responsive: 'The popover fits the field width and the control remains density-aware.',
    example: '<Combobox label="Category" value={value} onChange={setValue} options={options} />',
  }),
  component({
    name: 'Alert',
    category: 'feedback',
    purpose: 'Shows persistent inline operational feedback.',
    useWhen: 'Use for information, success, warning, or errors that belong in page flow.',
    avoid: 'Do not use for transient confirmations; use Toast.',
    variants: ['info', 'success', 'warning', 'danger'],
    states: ['default', 'dismissible'],
    accessibility: 'Danger uses alert semantics; other tones use status semantics and never rely on color alone.',
    responsive: 'Content wraps and actions remain readable in narrow containers.',
    example: '<Alert tone="danger" title="Could not sync">Check the connection and retry.</Alert>',
  }),
  component({
    name: 'Toast',
    category: 'feedback',
    purpose: 'Confirms a brief outcome without moving page content.',
    useWhen: 'Use for saved, removed, copied, or similar transient outcomes, optionally with Undo.',
    avoid: 'Do not use for blocking errors or instructions the user must retain.',
    variants: ['info', 'success', 'warning', 'danger'],
    states: ['closed', 'open'],
    accessibility: 'Uses status or alert semantics and exposes labeled optional actions.',
    responsive: 'Positions within safe viewport bounds and remains readable on phone and kiosk.',
    example: '<Toast open={open} tone="success" message="Item removed" actionLabel="Undo" />',
  }),
  component({
    name: 'Progress',
    category: 'feedback',
    purpose: 'Shows determinate completion or indeterminate ongoing work.',
    useWhen: 'Use when progress duration or completion has meaningful user value.',
    avoid: 'Do not fake exact progress for an operation that cannot measure it.',
    variants: ['determinate', 'indeterminate'],
    states: ['active', 'complete'],
    accessibility: 'Uses native progress semantics and requires a label or aria-label.',
    responsive: 'Fills available width without inline layout calculations.',
    example: '<Progress label="Importing recipes" value={4} max={10} showValue />',
  }),
  component({
    name: 'Skeleton',
    category: 'feedback',
    purpose: 'Reserves stable content geometry while data loads.',
    useWhen: 'Use when the eventual content shape is known and loading is expected.',
    avoid: 'Do not use as generic decoration or for errors and empty states.',
    variants: ['default'],
    states: ['loading'],
    accessibility: 'Pair the containing region with an accessible loading status.',
    responsive: 'Consumer classes define a shape matching the responsive content.',
    example: '<Skeleton className="h-20 w-full" />',
  }),
  component({
    name: 'SkeletonRow',
    category: 'feedback',
    purpose: 'Reserves a standard avatar-and-copy row while loading.',
    useWhen: 'Use for lists whose loaded rows share the standard compact shape.',
    avoid: 'Do not use when the final geometry differs substantially.',
    variants: ['default'],
    states: ['loading'],
    accessibility: 'Place inside a status-labeled loading region.',
    responsive: 'Adapts to container width while preserving row rhythm.',
    example: '<div role="status" aria-label="Loading events"><SkeletonRow /></div>',
  }),
  component({
    name: 'EmptyState',
    category: 'feedback',
    purpose: 'Explains empty or failed content and offers one useful recovery action.',
    useWhen: 'Use when a bounded page or section has no data or could not load.',
    avoid: 'Do not show empty copy before loading completes or hide actionable errors.',
    variants: ['empty', 'error'],
    states: ['empty', 'error'],
    accessibility: 'Use concrete titles and truthful action labels; icons are supplementary.',
    responsive: 'Centers readable copy and wraps its action safely.',
    example: '<EmptyState title="No saved places" action={<Button>Add place</Button>} />',
  }),
  component({
    name: 'DateTimeDial',
    category: 'form',
    purpose: 'Provides touch-first date and time adjustment for event workflows.',
    useWhen: 'Use for event start/end editing where quick stepped changes matter.',
    avoid: 'Do not use for read-only calendar metadata or arbitrary date ranges.',
    variants: ['date', 'time', 'date-time'],
    states: ['default', 'focus-visible', 'disabled'],
    accessibility: 'All increment/decrement actions have explicit names and preserve keyboard operation.',
    responsive: 'Controls use density-aware targets suitable for phone and kiosk touch.',
    example: '<DateTimeDial label="Starts" value={start} onChange={setStart} />',
  }),
  component({
    name: 'DisclosureSection',
    category: 'layout',
    purpose: 'Progressively reveals optional or advanced content.',
    useWhen: 'Use to keep infrequent settings available without overwhelming the main workflow.',
    avoid: 'Do not hide required fields, errors, or core actions.',
    variants: ['default'],
    states: ['collapsed', 'expanded', 'focus-visible', 'disabled'],
    accessibility: 'The trigger exposes expanded state and controls the labeled content region.',
    responsive: 'Expanded content stays in normal flow and follows container width.',
    example: '<DisclosureSection title="Advanced options">...</DisclosureSection>',
  }),
  component({
    name: 'FormSummaryCard',
    category: 'form',
    purpose: 'Summarizes pending form choices before a consequential submission.',
    useWhen: 'Use when users benefit from reviewing key values before saving.',
    avoid: 'Do not duplicate a short obvious form or replace field-level validation.',
    variants: ['default'],
    states: ['default'],
    accessibility: 'Uses readable label/value pairs in logical review order.',
    responsive: 'Stacks summary rows cleanly in narrow forms.',
    example: '<FormSummaryCard title="Event summary" items={summaryItems} />',
  }),
  component({
    name: 'ConfirmationDialog',
    category: 'workflow',
    purpose: 'Confirms a consequential or destructive action with explicit intent.',
    useWhen: 'Use before irreversible, destructive, or high-impact actions.',
    avoid: 'Do not confirm routine reversible actions; prefer Toast with Undo.',
    variants: ['standard', 'destructive'],
    states: ['closed', 'open', 'loading'],
    accessibility: 'Builds on Modal focus semantics; loading prevents accidental dismissal and duplicate confirmation.',
    responsive: 'Uses a small viewport-safe modal and stacked actions on narrow screens.',
    example: '<ConfirmationDialog open={open} title="Remove item?" description="This cannot be undone." destructive onConfirm={remove} onClose={close} />',
  }),
  component({
    name: 'ContentSection',
    category: 'layout',
    purpose: 'Composes a standard or dense titled section with optional action and surface.',
    useWhen: 'Use for repeated settings, list, and grouped content sections.',
    avoid: 'Do not hand-roll card headers, divider rhythm, or dense section spacing.',
    variants: ['standard', 'dense', 'card', 'plain'],
    states: ['default'],
    accessibility: 'Card surfaces expose a region; headings preserve content hierarchy.',
    responsive: 'Actions and content wrap within the available page measure.',
    example: '<ContentSection title="Household" density="dense">...</ContentSection>',
  }),
  component({
    name: 'MasterDetailLayout',
    category: 'layout',
    purpose: 'Composes responsive navigation/master content beside a detail panel.',
    useWhen: 'Use for Settings-like collections where users select one detail route.',
    avoid: 'Do not use for unrelated sidebars or three-rail dashboards.',
    variants: ['master-mobile', 'detail-mobile', 'split-desktop'],
    states: ['master', 'detail'],
    accessibility: 'Master and detail preserve DOM order and independent landmark semantics supplied by consumers.',
    responsive: 'Shows configured master/detail panels on mobile and both from tablet upward.',
    example: '<MasterDetailLayout master={<SettingsNav />} detail={<Outlet />} showMasterOnMobile={isRoot} showDetailOnMobile={!isRoot} />',
  }),
  component({
    name: 'PageFeedback',
    category: 'feedback',
    purpose: 'Provides one page-level contract for loading, empty, error, and success states.',
    useWhen: 'Use when an entire page or major section is waiting or cannot show normal content.',
    avoid: 'Do not render success-shaped fallbacks for errors or mix loading and empty states.',
    variants: ['loading', 'empty', 'error', 'success'],
    states: ['loading', 'empty', 'error', 'success'],
    accessibility: 'Loading and success use status semantics; errors use the EmptyState error contract with explicit recovery.',
    responsive: 'Uses fluid containers and shared readable feedback geometry.',
    example: '<PageFeedback state="error" title="Could not load calendar" action={<Button>Retry</Button>} />',
  }),
  component({
    name: 'PageHeader',
    category: 'layout',
    purpose: 'Composes a standard page title, description, optional icon/eyebrow, and actions.',
    useWhen: 'Use at the top of standard routed pages and within PageShell.',
    avoid: 'Do not hand-roll competing page title/action alignment.',
    variants: ['default', 'icon', 'eyebrow', 'actions'],
    states: ['default'],
    accessibility: 'Icons are decorative; consumers should preserve one clear page heading.',
    responsive: 'Actions stack below the title on narrow screens and align opposite it on wider screens.',
    example: '<PageHeader title="Saved places" description="Locations used for planning." actions={<Button>Add place</Button>} />',
  }),
  component({
    name: 'PrimaryRail',
    category: 'layout',
    purpose: 'Provides the flexible center content rail in the Home shell.',
    useWhen: 'Use for the central scroll/content area beside fixed proportional context rails.',
    avoid: 'Do not assign an explicit competing width or omit min-width containment.',
    variants: ['default'],
    states: ['default'],
    accessibility: 'Consumers provide the appropriate main or section landmarks.',
    responsive: 'Fills remaining space; with the app navigation and SecondaryRail it resolves to 55% desktop width.',
    example: '<PrimaryRail className="overflow-y-auto">...</PrimaryRail>',
  }),
  component({
    name: 'SecondaryRail',
    category: 'layout',
    purpose: 'Provides the contextual right rail in the Home shell.',
    useWhen: 'Use for desktop-only contextual summaries and secondary actions.',
    avoid: 'Do not replace shrink-0 with flex-none; Tailwind merging would discard the required percentage basis.',
    variants: ['desktop'],
    states: ['hidden-mobile', 'visible-desktop'],
    accessibility: 'Renders as aside; content must remain available elsewhere when hidden on mobile.',
    responsive: 'Hidden below lg; uses 5/16 of the post-navigation width, equal to 25% of the full shell.',
    example: '<SecondaryRail className="flex-col border-l">...</SecondaryRail>',
  }),
  component({
    name: 'SectionHeader',
    category: 'layout',
    purpose: 'Composes consistent section title, description, icon, and action alignment.',
    useWhen: 'Use above grouped page content or inside ContentSection.',
    avoid: 'Do not recreate uppercase compact labels or icon circles locally.',
    variants: ['standard', 'compact'],
    states: ['default'],
    accessibility: 'Icons are decorative and the title remains visible text.',
    responsive: 'Title content truncates safely while actions remain reachable.',
    example: '<SectionHeader icon={Palette} title="Theme" description="Choose the room tone." />',
  }),
  component({
    name: 'ThreeRailLayout',
    category: 'layout',
    purpose: 'Composes a responsive 20% navigation, 55% primary, and 25% context shell.',
    useWhen: 'Use for a full-width dashboard that needs persistent navigation and contextual rails.',
    avoid: 'Do not use on narrow pages or introduce independent fixed rail widths.',
    variants: ['mobile-primary', 'desktop-three-rail'],
    states: ['default'],
    accessibility: 'Consumers provide navigation, main, and aside landmarks within each slot.',
    responsive: 'Mobile shows primary content; desktop uses 20/55/25 proportional rails.',
    example: '<ThreeRailLayout navigation={<Nav />} primary={<Main />} secondary={<Context />} />',
  }),
  component({
    name: 'WorkflowActions',
    category: 'workflow',
    purpose: 'Aligns cancel and commit actions consistently at the end of a modal, sheet, or form.',
    useWhen: 'Use for paired workflow actions after the workflow content.',
    avoid: 'Do not change action order per viewport or place primary action before cancel in DOM order.',
    variants: ['default'],
    states: ['default'],
    accessibility: 'Preserves logical cancel-then-confirm DOM order and visible labels.',
    responsive: 'Stacks full-width in reverse visual order on narrow screens and aligns right on wider screens.',
    example: '<WorkflowActions><Button variant="secondary">Cancel</Button><Button>Save</Button></WorkflowActions>',
  }),
]

export const DESIGN_SYSTEM_CHANGELOG = [
  {
    version: '1.0.1',
    date: '2026-07-10',
    changes: [
      'Added explicit center, start, and between Button content alignment contracts.',
      'Aligned the Home Family sidebar heading and member rows to one shared inset.',
    ],
  },
  {
    version: '1.0.0',
    date: '2026-07-10',
    changes: [
      'Documented all public UI primitives and composition patterns.',
      'Added machine-readable component manifest and version metadata.',
      'Added semantic surface, content, and action aliases.',
      'Standardized active product surfaces on shared design contracts.',
    ],
  },
  {
    version: '0.3.0',
    date: '2026-07-10',
    changes: [
      'Added reusable three-rail, master-detail, page header, content section, feedback, and confirmation patterns.',
    ],
  },
  {
    version: '0.2.0',
    date: '2026-07-10',
    changes: [
      'Completed shared primitive adoption across active Home, Calendar, Grocery, Cooking, Settings, and shell surfaces.',
    ],
  },
  {
    version: '0.1.0',
    date: '2026-07-10',
    changes: [
      'Established token generation, style-debt reporting, density profiles, and portable design-system export.',
    ],
  },
]

export function renderComponentGuide() {
  const sections = COMPONENT_MANIFEST.map((entry) => `## ${entry.name}

**Purpose:** ${entry.purpose}

**Use when:** ${entry.useWhen}

**Avoid:** ${entry.avoid}

**Variants:** ${entry.variants.join(', ')}

**States:** ${entry.states.join(', ')}

**Accessibility:** ${entry.accessibility}

**Responsive behavior:** ${entry.responsive}

\`\`\`tsx
${entry.example}
\`\`\``)

  return `# Casa Tabor Component Guide

Design system version: ${DESIGN_SYSTEM_VERSION}

${sections.join('\n\n')}
`
}

export function renderDesignSystemChangelog() {
  return `# Casa Tabor Design System Changelog

${DESIGN_SYSTEM_CHANGELOG.map((release) => `## ${release.version} - ${release.date}

${release.changes.map((change) => `- ${change}`).join('\n')}`).join('\n\n')}
`
}
