import { DEFAULT_THEME_COLORS } from './tokens.mjs'

export const APPEARANCE_PRESETS = [
  {
    id: 'default',
    label: 'Default',
    description: 'Warm ivory, heritage navy, and aged brass',
    colors: { ...DEFAULT_THEME_COLORS },
  },
  {
    id: 'espresso',
    label: 'Espresso',
    description: 'Dark umber, parchment, and burnished cognac',
    colors: {
      'casa-gold': '#C69A6B',
      'casa-navy': '#4A2F20',
      'casa-bg': '#EDE5D8',
      'casa-bg-2': '#E4D9CA',
      'casa-surface': '#F7F2EA',
      'casa-text': '#2C1A0E',
      'casa-border': '#D4C8B8',
      'casa-error': '#A94F43',
      'casa-success': '#4F8060',
      'casa-warning': '#B9783F',
      'casa-surface-subtle': '#F1E9DD',
      'casa-control-border': '#CCBDAA',
      'casa-divider-strong': '#D4C5B2',
      'casa-text-secondary': '#5A4635',
      'casa-text-tertiary': '#7C6856',
      'casa-text-faint': '#9A8878',
      'casa-accent-soft': '#ECD7C1',
      'casa-accent-soft-border': '#D8B48E',
      'casa-accent-soft-hover': '#E3C5A8',
      'casa-accent-subtle': '#F3E5D7',
      'casa-accent-subtle-border': '#DFC5A8',
      'casa-info': '#4F7C7D',
      'casa-info-strong': '#31595A',
      'casa-info-soft': '#DBE8E7',
      'casa-success-strong': '#396348',
      'casa-success-soft': '#DCE8DD',
      'casa-toggle-track': '#E2D7C8',
      'casa-top-pick-band': '#75402E',
    },
  },
  {
    id: 'liv-blush',
    label: 'Liv Blush',
    description: 'Dusty rose, soft plaster, and smoked berry',
    colors: {
      'casa-gold': '#D8A6AF',
      'casa-navy': '#50343D',
      'casa-bg': '#F8F1F0',
      'casa-bg-2': '#EFE3E2',
      'casa-surface': '#FFF9F8',
      'casa-text': '#35282C',
      'casa-border': '#DFCECE',
      'casa-error': '#A94F4D',
      'casa-success': '#4F8068',
      'casa-warning': '#B47A54',
      'casa-surface-subtle': '#F5E9E8',
      'casa-control-border': '#D8C3C4',
      'casa-divider-strong': '#DDC9CA',
      'casa-text-secondary': '#655158',
      'casa-text-tertiary': '#897078',
      'casa-text-faint': '#A68F95',
      'casa-accent-soft': '#EED5D9',
      'casa-accent-soft-border': '#DDBAC1',
      'casa-accent-soft-hover': '#E6C7CD',
      'casa-accent-subtle': '#F5E5E8',
      'casa-accent-subtle-border': '#E4C8CE',
      'casa-info': '#6F7F8F',
      'casa-info-strong': '#4D5966',
      'casa-info-soft': '#E7EAED',
      'casa-success-strong': '#3D6753',
      'casa-success-soft': '#DEEAE3',
      'casa-toggle-track': '#E7DADB',
      'casa-top-pick-band': '#6D4651',
    },
  },
  {
    id: 'kitchen-teal',
    label: 'Kitchen Teal',
    description: 'Glazed teal, limestone, and unlacquered brass',
    colors: {
      'casa-gold': '#C8B28A',
      'casa-navy': '#1F4744',
      'casa-bg': '#F1F3EE',
      'casa-bg-2': '#E5E9E2',
      'casa-surface': '#FBFCF9',
      'casa-text': '#263330',
      'casa-border': '#CDD7CF',
      'casa-error': '#A6544C',
      'casa-success': '#3F8063',
      'casa-warning': '#B47D48',
      'casa-surface-subtle': '#EAF0EB',
      'casa-control-border': '#C2CEC6',
      'casa-divider-strong': '#C8D4CB',
      'casa-text-secondary': '#4D625E',
      'casa-text-tertiary': '#71827E',
      'casa-text-faint': '#91A09C',
      'casa-accent-soft': '#E2D7C0',
      'casa-accent-soft-border': '#CCB98F',
      'casa-accent-soft-hover': '#D8C8A8',
      'casa-accent-subtle': '#EEE7D8',
      'casa-accent-subtle-border': '#D8C9AC',
      'casa-info': '#3F8586',
      'casa-info-strong': '#285E60',
      'casa-info-soft': '#DDECEC',
      'casa-success-strong': '#2F674E',
      'casa-success-soft': '#DCEADF',
      'casa-toggle-track': '#DCE4DE',
      'casa-top-pick-band': '#58674B',
    },
  },
  {
    id: 'belgian-linen',
    label: 'Belgian Linen',
    description: 'Flax, smoked plum, and sun-washed clay',
    colors: {
      'casa-gold': '#D09A8B',
      'casa-navy': '#49343E',
      'casa-bg': '#F3F0EA',
      'casa-bg-2': '#E8E3DA',
      'casa-surface': '#FBF9F5',
      'casa-text': '#312F2B',
      'casa-border': '#D8D0C4',
      'casa-error': '#A65349',
      'casa-success': '#5E7D61',
      'casa-warning': '#AF7C48',
      'casa-surface-subtle': '#EEEAE3',
      'casa-control-border': '#CEC5B8',
      'casa-divider-strong': '#D3CABC',
      'casa-text-secondary': '#5F5A52',
      'casa-text-tertiary': '#817A70',
      'casa-text-faint': '#9D958A',
      'casa-accent-soft': '#EBD8D1',
      'casa-accent-soft-border': '#D9B4A9',
      'casa-accent-soft-hover': '#E2C5BC',
      'casa-accent-subtle': '#F3E7E2',
      'casa-accent-subtle-border': '#DFC8C0',
      'casa-info': '#648184',
      'casa-info-strong': '#455E60',
      'casa-info-soft': '#E0E9E8',
      'casa-success-strong': '#48624A',
      'casa-success-soft': '#E1E9DF',
      'casa-toggle-track': '#E2DDD4',
      'casa-top-pick-band': '#76554F',
    },
  },
  {
    id: 'weathered-olive',
    label: 'Weathered Olive',
    description: 'Moss, bone, and antique celadon',
    colors: {
      'casa-gold': '#B8AD7E',
      'casa-navy': '#35422F',
      'casa-bg': '#F1F1E9',
      'casa-bg-2': '#E5E6DA',
      'casa-surface': '#FAFAF4',
      'casa-text': '#2E322A',
      'casa-border': '#D2D5C5',
      'casa-error': '#A65248',
      'casa-success': '#5B7D56',
      'casa-warning': '#AF7D45',
      'casa-surface-subtle': '#EAECDF',
      'casa-control-border': '#C7CBB9',
      'casa-divider-strong': '#CDD1BE',
      'casa-text-secondary': '#596052',
      'casa-text-tertiary': '#7A8270',
      'casa-text-faint': '#979E8D',
      'casa-accent-soft': '#E4E0C9',
      'casa-accent-soft-border': '#C8BE91',
      'casa-accent-soft-hover': '#D9D3B3',
      'casa-accent-subtle': '#EFEDDF',
      'casa-accent-subtle-border': '#D4CEAA',
      'casa-info': '#5A7C7D',
      'casa-info-strong': '#3C595A',
      'casa-info-soft': '#DEE9E7',
      'casa-success-strong': '#456342',
      'casa-success-soft': '#DFE9DC',
      'casa-toggle-track': '#DDE1D2',
      'casa-top-pick-band': '#66704A',
    },
  },
  {
    id: 'slate-atelier',
    label: 'Slate Atelier',
    description: 'Blue slate, chalk, and oxidized pewter',
    colors: {
      'casa-gold': '#A9B9BD',
      'casa-navy': '#344852',
      'casa-bg': '#EEF0EE',
      'casa-bg-2': '#E1E5E3',
      'casa-surface': '#F9FAF8',
      'casa-text': '#293033',
      'casa-border': '#CDD3D1',
      'casa-error': '#A9534D',
      'casa-success': '#557C65',
      'casa-warning': '#AD7B4B',
      'casa-surface-subtle': '#E8ECEA',
      'casa-control-border': '#C2C9C7',
      'casa-divider-strong': '#C8CFCC',
      'casa-text-secondary': '#535F63',
      'casa-text-tertiary': '#748084',
      'casa-text-faint': '#929C9F',
      'casa-accent-soft': '#DCE4E3',
      'casa-accent-soft-border': '#B9C9C8',
      'casa-accent-soft-hover': '#CFDAD9',
      'casa-accent-subtle': '#E9EEEC',
      'casa-accent-subtle-border': '#C7D3D1',
      'casa-info': '#5B7F86',
      'casa-info-strong': '#3D5A60',
      'casa-info-soft': '#DFEAEC',
      'casa-success-strong': '#41634D',
      'casa-success-soft': '#DFE9E2',
      'casa-toggle-track': '#DCE1DF',
      'casa-top-pick-band': '#536A70',
    },
  },
]
