export const THEME_COLOR_KEYS = [
  'casa-gold',
  'casa-navy',
  'casa-bg',
  'casa-bg-2',
  'casa-surface',
  'casa-text',
  'casa-border',
  'casa-error',
  'casa-success',
  'casa-warning',
  'casa-surface-subtle',
  'casa-control-border',
  'casa-divider-strong',
  'casa-text-secondary',
  'casa-text-tertiary',
  'casa-text-faint',
  'casa-accent-soft',
  'casa-accent-soft-border',
  'casa-accent-soft-hover',
  'casa-accent-subtle',
  'casa-accent-subtle-border',
  'casa-info',
  'casa-info-strong',
  'casa-info-soft',
  'casa-success-strong',
  'casa-success-soft',
  'casa-toggle-track',
  'casa-top-pick-band',
]

export const DEFAULT_FONT_SCALE = 1
export const MIN_FONT_SCALE = 0.85
export const MAX_FONT_SCALE = 1.3

export const DEFAULT_THEME_COLORS = {
  'casa-gold': '#C9A96E',
  'casa-navy': '#1B2A4A',
  'casa-bg': '#FAF8F5',
  'casa-bg-2': '#F2EEE7',
  'casa-surface': '#FFFFFF',
  'casa-text': '#2D2D2D',
  'casa-border': '#E8E2D9',
  'casa-error': '#C0392B',
  'casa-success': '#27AE60',
  'casa-warning': '#E67E22',
  'casa-surface-subtle': '#FAF6EE',
  'casa-control-border': '#E3DACB',
  'casa-divider-strong': '#E4DBCB',
  'casa-text-secondary': '#5C5D66',
  'casa-text-tertiary': '#8D8E99',
  'casa-text-faint': '#A9A398',
  'casa-accent-soft': '#F4E2CD',
  'casa-accent-soft-border': '#E9CBA6',
  'casa-accent-soft-hover': '#EFD6BB',
  'casa-accent-subtle': '#FAF0E2',
  'casa-accent-subtle-border': '#EBD9BF',
  'casa-info': '#10A5AC',
  'casa-info-strong': '#0A6266',
  'casa-info-soft': '#E7F4F4',
  'casa-success-strong': '#2A6A34',
  'casa-success-soft': '#DBF0DC',
  'casa-toggle-track': '#EDE7DA',
  'casa-top-pick-band': '#8A5A1E',
}

export const MIDNIGHT_THEME_COLORS = {
  'casa-gold': '#9F8658',
  'casa-navy': '#0E1218',
  'casa-bg': '#090C11',
  'casa-bg-2': '#070A0F',
  'casa-surface': '#121923',
  'casa-text': '#E3DDD1',
  'casa-border': '#263244',
  'casa-error': '#C96A5E',
  'casa-success': '#4AA56A',
  'casa-warning': '#D2A465',
  'casa-surface-subtle': '#171F2C',
  'casa-control-border': '#324157',
  'casa-divider-strong': '#2B374C',
  'casa-text-secondary': '#BCC7D8',
  'casa-text-tertiary': '#93A4BC',
  'casa-text-faint': '#7D8EA7',
  'casa-accent-soft': '#5A4A33',
  'casa-accent-soft-border': '#7A6242',
  'casa-accent-soft-hover': '#6A563C',
  'casa-accent-subtle': '#342C23',
  'casa-accent-subtle-border': '#4A3C2E',
  'casa-info': '#57C9C9',
  'casa-info-strong': '#8EE3E3',
  'casa-info-soft': '#1B3A40',
  'casa-success-strong': '#7BD58B',
  'casa-success-soft': '#1E3D28',
  'casa-toggle-track': '#303B4E',
  'casa-top-pick-band': '#F0C98F',
}

export const ROOM_TONE_COLORS = {
  day: '#FAF8F5',
  afternoon: '#FDF4E7',
  evening: '#F5E6CC',
  night: '#2A1F0E',
  'late-night': '#120D06',
  manual: '#E8D5B0',
}

export const DESIGN_TOKENS = {
  staticColor: {
    'casa-on-dark': '#FFFFFF',
    'family-jake': '#1B2A4A',
    'family-kelly': '#C4693A',
    'family-liv': '#6A9E7F',
    'family-emme': '#C47A8A',
    'family-owen': '#D4A44C',
    'night-bg': '#1A1A2E',
    'night-surface': '#16213E',
    'night-text': '#E0D8CC',
    'night-muted': '#6B6B7B',
    'night-border': '#2A2A3E',
    'night-gold': '#A08050',
  },
  fontFamily: {
    display: "'Cormorant Garamond', Georgia, serif",
    body: "'DM Sans', system-ui, sans-serif",
    mono: "'JetBrains Mono', monospace",
  },
  type: {
    'display-xl': { touch: 'clamp(52px, calc(46px + 1.45vw), 72px)', compact: '52px', kiosk: '76px', lineHeight: '1.1' },
    'display-lg': { touch: 'clamp(40px, calc(36px + 1.1vw), 58px)', compact: '40px', kiosk: '60px', lineHeight: '1.15' },
    'display-md': { touch: 'clamp(32px, calc(28px + 0.82vw), 44px)', compact: '32px', kiosk: '46px', lineHeight: '1.2' },
    'display-sm': { touch: 'clamp(26px, calc(23px + 0.65vw), 36px)', compact: '26px', kiosk: '38px', lineHeight: '1.25' },
    heading: { touch: 'clamp(23px, calc(21px + 0.5vw), 30px)', compact: '23px', kiosk: '32px', lineHeight: '1.3' },
    'body-lg': { touch: 'clamp(19px, calc(18px + 0.4vw), 24px)', compact: '19px', kiosk: '26px', lineHeight: '1.5' },
    body: { touch: 'clamp(17px, calc(16px + 0.34vw), 21px)', compact: '17px', kiosk: '23px', lineHeight: '1.5' },
    'body-sm': { touch: 'clamp(15px, calc(14px + 0.3vw), 19px)', compact: '15px', kiosk: '21px', lineHeight: '1.45' },
    caption: { touch: 'clamp(14px, calc(13px + 0.24vw), 17px)', compact: '14px', kiosk: '18px', lineHeight: '1.4' },
  },
  spacing: {
    'nav-height': '4.5rem',
    'topbar-height': '3rem',
    'page-gutter': 'var(--ds-page-gutter)',
    'section-gap': 'clamp(1rem, 2vw, 1.5rem)',
    'card-padding': 'clamp(0.875rem, 1.5vw, 1.25rem)',
  },
  layout: {
    breakpointTablet: '48rem',
    breakpointWide: '80rem',
    gutterPhone: '1rem',
    gutterTablet: '1.5rem',
    gutterWide: '2rem',
  },
  container: {
    'page-narrow': '48rem',
    page: '80rem',
    'page-wide': '96rem',
  },
  controls: {
    compact: { target: '44px', sm: '36px', md: '40px', lg: '44px' },
    touch: { target: '44px', sm: '40px', md: '44px', lg: '48px' },
    kiosk: { target: '48px', sm: '44px', md: '48px', lg: '56px' },
  },
  radius: {
    button: '0.5rem',
    card: '0.75rem',
    modal: '1rem',
    pill: '9999px',
  },
  shadow: {
    card: '0 1px 3px rgba(27,42,74,0.06), 0 1px 2px rgba(27,42,74,0.04)',
    'card-hover': '0 4px 12px rgba(27,42,74,0.08)',
    modal: '0 8px 30px rgba(27,42,74,0.12)',
    fab: '0 4px 14px rgba(201,169,110,0.3)',
  },
  midnightShadow: {
    card: '0 1px 3px rgba(0,0,0,0.45), 0 1px 2px rgba(0,0,0,0.35)',
    'card-hover': '0 6px 18px rgba(0,0,0,0.55)',
    modal: '0 12px 36px rgba(0,0,0,0.65)',
    fab: '0 6px 18px rgba(159,134,88,0.40)',
  },
  motion: {
    fast: '120ms',
    normal: '220ms',
    slow: '350ms',
    'room-tone': '2000ms',
    ambient: '5000ms',
    'ease-standard': 'cubic-bezier(0.2, 0, 0, 1)',
    'ease-emphasized': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
  },
  zIndex: {
    base: '0',
    raised: '10',
    sticky: '20',
    dropdown: '30',
    scrim: '40',
    modal: '50',
    popover: '60',
    toast: '70',
    debug: '90',
  },
}
