export const VISUAL_MATRIX = [
  {
    name: 'mobile-day-touch',
    viewport: { width: 390, height: 844 },
    theme: 'day',
    density: 'touch',
    hasTouch: true,
    isMobile: true,
  },
  {
    name: 'mobile-midnight-touch',
    viewport: { width: 390, height: 844 },
    theme: 'midnight',
    density: 'touch',
    hasTouch: true,
    isMobile: true,
  },
  {
    name: 'desktop-day-compact',
    viewport: { width: 1440, height: 1000 },
    theme: 'day',
    density: 'compact',
    hasTouch: false,
    isMobile: false,
  },
  {
    name: 'desktop-midnight-compact',
    viewport: { width: 1440, height: 1000 },
    theme: 'midnight',
    density: 'compact',
    hasTouch: false,
    isMobile: false,
  },
  {
    name: 'kiosk-day-kiosk',
    viewport: { width: 2560, height: 1440 },
    theme: 'day',
    density: 'kiosk',
    hasTouch: true,
    isMobile: false,
  },
  {
    name: 'kiosk-midnight-kiosk',
    viewport: { width: 2560, height: 1440 },
    theme: 'midnight',
    density: 'kiosk',
    hasTouch: true,
    isMobile: false,
  },
]
