import { expect, test } from '@playwright/test'

// Recipes V2 (canvas row 49; Jake, Oct 6: "make sure you check all the screens, and any model or action buttons to
// make sure they are styled and working as they should"). The family's recipes as of Oct 6, in memory.

const PHONE = { width: 390, height: 844 }
const WALL = { width: 1920, height: 1080 }
const open = async (page, at, { size = PHONE, wall = false, cooking = '' } = {}) => {
  await page.setViewportSize(size)
  await page.goto(`/__recipes-fixture?at=${encodeURIComponent(at)}${wall ? '&wall=1' : ''}${cooking ? `&cooking=${cooking}` : ''}`)
  const root = page.getByTestId('recipes-fixture')
  await expect(root).toBeAttached()
  await page.evaluate(() => document.fonts.ready)
  return root
}

test('recipes: the photo wall — favorites first, a star, the chips, search by name or ingredient', { tag: '@smoke' }, async ({ page }) => {
  const s = await open(page, '/recipes')
  const list = s.getByRole('list', { name: 'Recipes' })
  await expect(list.getByRole('listitem')).toHaveCount(10)
  await expect(list.getByRole('listitem').first()).toContainText('Shrimp and Broccoli Stir Fry')
  await expect(list.getByRole('listitem').nth(1)).toContainText('30 min · made 3 times · last Aug 14')
  await expect(page).toHaveScreenshot('recipes-phone-wall.png')
  // A star: the bowls join the favorites (and the chip counts them).
  await s.getByRole('button', { name: 'Star Quick Salmon Power Bowls' }).click()
  await s.getByRole('button', { name: /Favorites · 3/ }).click()
  await expect(list.getByRole('listitem')).toHaveCount(3)
  await s.getByRole('button', { name: /Favorites · 3/ }).click()
  await s.getByRole('button', { name: 'Quick', exact: true }).click()
  await expect(list.getByRole('listitem')).toHaveCount(5)
  await s.getByRole('button', { name: 'All 10' }).click()
  await s.getByRole('textbox', { name: 'Search recipes' }).fill('spaghetti')
  await expect(list.getByRole('listitem')).toHaveCount(1)
  await s.getByRole('textbox', { name: 'Search recipes' }).fill('pancakes')
  await expect(s.getByText('Nothing called “pancakes”, or with it in. Try an ingredient.')).toBeVisible()
  await s.getByRole('button', { name: 'Clear the search' }).click()
  await expect(list.getByRole('listitem')).toHaveCount(10)
})

test('recipes: a recipe — serves 4 doubles the card’s amounts; Groceries adds what you tick', async ({ page }) => {
  const s = await open(page, '/recipes/scampi')
  const ingredients = s.getByRole('region', { name: 'Ingredients' })
  await expect(ingredients).toContainText('10 oz Shrimp')
  await expect(ingredients).toContainText('2 cloves Garlic')
  await expect(page).toHaveScreenshot('recipes-phone-recipe.png')
  await s.getByRole('button', { name: '4', exact: true }).click()
  await expect(ingredients).toContainText('20 oz Shrimp')
  await expect(s.getByRole('button', { name: '4', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await s.getByRole('button', { name: 'Groceries' }).click()
  const sheet = page.getByRole('dialog', { name: 'Add to Groceries' })
  await sheet.getByRole('button', { name: '1/2 Broccoli' }).click()
  await expect(sheet.getByRole('button', { name: 'Add 7 to Groceries' })).toBeVisible()
  await sheet.getByRole('button', { name: 'Add 7 to Groceries' }).click()
  await expect(page.getByText('7 on the grocery list.')).toBeVisible()
  const added = await page.evaluate(() => window.__recipes.groceries)
  expect(added).toContain('20 oz Shrimp')
  expect(added).not.toContain('1/2 Broccoli')
})

test('recipes: Groceries starts with the pantry things unticked', async ({ page }) => {
  const s = await open(page, '/recipes/stirfry')
  await s.getByRole('button', { name: 'Groceries' }).click()
  const sheet = page.getByRole('dialog', { name: 'Add to Groceries' })
  await expect(sheet.getByRole('button', { name: '1 tbsp vegetable oil' })).toHaveAttribute('aria-pressed', 'false')
  await expect(sheet.getByRole('button', { name: 'Add 4 to Groceries' })).toBeVisible()
})

test('recipes: cooking on the phone — a step’s own timer, ticks, next and back, done counts it', async ({ page }) => {
  const s = await open(page, '/recipes/scampi/cook', { cooking: 'phone' })
  await expect(s.getByText('STEP 5 OF 11')).toBeVisible()
  await expect(s.getByLabel('Timers')).toContainText('9:42')
  await expect(page).toHaveScreenshot('recipes-phone-cook.png')
  await s.getByRole('button', { name: 'Start a 9–11 min timer' }).click()
  await expect(s.getByLabel('Timers')).toContainText('9:00')
  await expect(s.getByRole('button', { name: 'Start a 9–11 min timer' })).toHaveCount(0)
  await s.getByRole('region', { name: 'For this step' }).getByRole('button', { name: '6 oz Spaghetti' }).click()
  await expect(s.getByText('All ingredients · 6 of 8 ready')).toBeVisible()
  await s.getByRole('button', { name: 'Next step' }).click()
  await expect(s.getByText('STEP 6 OF 11')).toBeVisible()
  await s.getByRole('button', { name: 'Back', exact: true }).click()
  await expect(s.getByText('STEP 5 OF 11')).toBeVisible()
  await s.getByRole('button', { name: 'All steps' }).click()
  await page.getByRole('dialog', { name: 'All steps' }).getByRole('button', { name: /^11 Divide pasta/ }).click()
  await expect(s.getByText('STEP 11 OF 11')).toBeVisible()
  await s.getByRole('button', { name: 'Done cooking' }).click()
  await expect(page.getByText('Made it. That’s 4 times.')).toBeVisible()
  await expect(page.getByRole('article', { name: 'Garlic Butter Shrimp Scampi' })).toContainText('made 4 times · last today')
})

test('recipes: on the wall — the photo wall says what the phone is cooking; Open here picks it up at step 5', { tag: '@smoke' }, async ({ page }) => {
  const s = await open(page, '/recipes', { size: WALL, wall: true, cooking: 'phone' })
  await expect(s.getByText('Cooking on Jake’s phone:')).toBeVisible()
  await expect(page).toHaveScreenshot('recipes-wall.png')
  await s.getByRole('button', { name: 'Open here' }).click()
  await expect(s.getByText('STEP 5 OF 11')).toBeVisible()
  await expect(s.getByRole('region', { name: 'Ingredients' }).getByText('This step')).toBeVisible()
  await expect(page).toHaveScreenshot('recipes-wall-cook.png')
})

test('recipes: adding from a link — it reads it, you check it, it saves and opens', async ({ page }) => {
  const s = await open(page, '/recipes/new')
  const sheet = page.getByRole('dialog', { name: 'Add a recipe' })
  await expect(sheet).toContainText('3 of yours came this way')
  await expect(page).toHaveScreenshot('recipes-phone-add.png')
  await sheet.getByRole('button', { name: /Paste a link/ }).click()
  await sheet.getByRole('textbox', { name: 'The recipe’s link' }).fill('https://example.com/nothing-here')
  await sheet.getByRole('button', { name: 'Read it' }).click()
  await expect(sheet.getByRole('alert')).toContainText('No recipe was found there.')
  await sheet.getByRole('textbox', { name: 'The recipe’s link' }).fill('https://example.com/pancakes')
  await sheet.getByRole('button', { name: 'Read it' }).click()
  const editor = s.getByRole('region', { name: 'Check the recipe' })
  await expect(editor.getByRole('textbox', { name: 'Name' })).toHaveValue('Lemon Ricotta Pancakes')
  await expect(editor).toContainText('Read from your link.')
  await editor.getByRole('button', { name: 'Save' }).first().click()
  await expect(page.getByRole('article', { name: 'Lemon Ricotta Pancakes' })).toBeVisible()
  await expect(page.getByText('Saved.')).toBeVisible()
})

test('recipes: typing one in — a name is needed; steps move and go; it saves', async ({ page }) => {
  const s = await open(page, '/recipes/new')
  await page.getByRole('dialog', { name: 'Add a recipe' }).getByRole('button', { name: /Type it in/ }).click()
  const editor = s.getByRole('region', { name: 'New recipe' })
  await editor.getByRole('button', { name: 'Save' }).first().click()
  await expect(editor.getByText('It needs a name.')).toBeVisible()
  await editor.getByRole('textbox', { name: 'Name' }).fill('Toast')
  await editor.getByRole('textbox', { name: 'Ingredients, one per line' }).fill('2 slices bread\nButter')
  await editor.getByRole('textbox', { name: 'Step 1' }).fill('Butter it.')
  await editor.getByRole('button', { name: 'Add a step' }).click()
  await editor.getByRole('textbox', { name: 'Step 2' }).fill('Toast the bread.')
  await editor.getByRole('button', { name: 'Move step 2 up' }).click()
  await expect(editor.getByRole('textbox', { name: 'Step 1' })).toHaveValue('Toast the bread.')
  await editor.getByRole('button', { name: 'Save' }).first().click()
  const saved = await page.evaluate(() => window.__recipes.saved)
  expect(saved.steps).toEqual(['Toast the bread.', 'Butter it.'])
  expect(saved.ingredients).toEqual(['2 slices bread', 'Butter'])
  await expect(page.getByRole('article', { name: 'Toast' })).toBeVisible()
})

test('recipes: editing — rename, change the photo from its search, delete after a second tap', async ({ page }) => {
  const s = await open(page, '/recipes/scampi/edit')
  const editor = s.getByRole('region', { name: 'Edit recipe' })
  await expect(page).toHaveScreenshot('recipes-phone-edit.png')
  await editor.getByRole('textbox', { name: 'Name' }).fill('Shrimp Scampi')
  await editor.getByRole('button', { name: 'Change photo' }).click()
  const picker = page.getByRole('dialog', { name: 'Change photo' })
  await picker.getByRole('button', { name: 'Search' }).click()
  await picker.getByRole('button', { name: 'Use this photo' }).first().click()
  await editor.getByRole('button', { name: 'Save' }).first().click()
  await expect(page.getByRole('article', { name: 'Shrimp Scampi' })).toBeVisible()
  expect(await page.evaluate(() => window.__recipes.saved.image_url)).toBe('/fixtures/recipes/seared.jpg')
  await page.getByRole('button', { name: 'Delete' }).click()
  await page.getByRole('button', { name: 'Tap again to delete it' }).click()
  await expect(page.getByText('Deleted.')).toBeVisible()
  await expect(s.getByRole('list', { name: 'Recipes' }).getByRole('listitem')).toHaveCount(9)
})
