import { useState, useEffect } from 'react'
import { format, parseISO } from 'date-fns'
import { Settings, Bot, CalendarDays, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { cn } from '../utils/cn'
import AIAssistantFab from '../components/shared/AIAssistantFab'
import PrepAlertsSection from '../components/shared/PrepAlertsSection'
import ConflictAlertsSection from '../components/shared/ConflictAlertsSection'
import { useTodayEvents } from '../hooks/useCalendarEvents'
import { useFamilyMembers } from '../hooks/useFamilyMembers'
import { useHomeWeather } from '../hooks/useHomeWeather'
import { useLiveClock } from '../hooks/useLiveClock'

interface MemberEvent {
  title: string
  start_time: string
  end_time: string
  all_day: boolean
  location_name: string | null
  enrichment: { summary: string | null; category: string | null; what_to_bring: string[] | null } | null
}

interface MemberSchedule {
  name: string
  color_hex: string
  events: MemberEvent[]
}

interface Briefing {
  briefing_date: string
  summary_text: string | null
  member_schedules: Record<string, MemberSchedule>
  generated_by: string | null
}

export default function BriefingPage() {
  const [briefing, setBriefing] = useState<Briefing | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const today = new Date().toISOString().slice(0, 10)
  const now = useLiveClock(60_000)
  const { data: todayEvents } = useTodayEvents(now)
  const { data: family } = useFamilyMembers()
  const { data: weather } = useHomeWeather()

  useEffect(() => {
    loadBriefing()
  }, [])

  async function loadBriefing() {
    setIsLoading(true)
    setError(null)
    const { data } = await supabase
      .from('daily_briefings')
      .select('*')
      .eq('briefing_date', today)
      .maybeSingle()

    if (data) {
      setBriefing(data as Briefing)
      setIsLoading(false)
    } else {
      await generate()
    }
  }

  async function generate() {
    setIsGenerating(true)
    setError(null)
    try {
      const { data, error: fnErr } = await supabase.functions.invoke('generate-briefing')
      console.log('[Briefing] invoke result:', { data, error: fnErr })
      if (fnErr) {
        // FunctionInvokeError sometimes has context.message
        const msg = (fnErr as { context?: { message?: string }; message?: string })?.context?.message ?? fnErr.message ?? String(fnErr)
        throw new Error(msg)
      }
      if (data?.error) throw new Error(data.error)
      if (data?.briefing) setBriefing(data.briefing as Briefing)
      else throw new Error('No briefing returned from function')
    } catch (err) {
      console.error('[Briefing] generate error:', err)
      setError((err as Error).message ?? String(err))
    } finally {
      setIsGenerating(false)
      setIsLoading(false)
    }
  }

  const dateLabel = format(new Date(), 'EEEE, MMMM d')
  const memberList = briefing ? Object.values(briefing.member_schedules).filter(m => m.events.length > 0) : []
  const emptyMembers = briefing ? Object.values(briefing.member_schedules).filter(m => m.events.length === 0) : []

  return (
    <div className="max-w-2xl mx-auto p-6 space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="font-display text-display-md text-casa-navy">{dateLabel}</h1>
          <p className="text-caption text-casa-muted mt-1">
            {briefing?.generated_by ? `Generated by ${briefing.generated_by}` : 'Daily Briefing'}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Link
            to="/settings/ai"
            className="p-2 rounded-button border border-casa-border text-casa-muted hover:text-casa-navy hover:bg-casa-bg transition-colors"
            title="AI Settings"
          >
            <Settings size={15} />
          </Link>
          <button
            onClick={generate}
            disabled={isGenerating}
            className={cn(
              'inline-flex items-center gap-2 px-3 py-1.5 rounded-button border text-body-sm font-semibold disabled:opacity-50 transition-all',
              isGenerating
                ? 'ai-thinking text-casa-gold border-transparent'
                : 'border-casa-border text-casa-navy hover:bg-casa-bg',
            )}
          >
            <Sparkles size={13} className={cn(isGenerating && 'animate-pulse')} />
            {isGenerating ? 'AI is thinking…' : 'Regenerate'}
          </button>
        </div>
      </div>

      {(isLoading || isGenerating) && !briefing && (
        <div className="ai-thinking bg-casa-surface rounded-card p-8 text-center space-y-3 shadow-card">
          <Bot size={28} className="mx-auto text-casa-gold animate-pulse" />
          <p className="text-body text-casa-muted">AI is thinking up your briefing…</p>
        </div>
      )}

      {/* ── Conflict alerts (grouped, collapsible) ────────────── */}
      <ConflictAlertsSection />

      {error && (
        <div className="bg-red-50 border border-red-200 rounded-card p-4 text-body-sm text-casa-error">
          {error} — <Link to="/settings/ai" className="underline">check AI settings</Link>
        </div>
      )}

      {/* ── Prep & Readiness alerts ───────────────────────────── */}
      <PrepAlertsSection />

      {briefing && (
        <>
          {briefing.summary_text ? (
            <div className="bg-casa-surface rounded-card border border-casa-border p-5 shadow-card">
              <div className="flex items-center gap-2 mb-3">
                <Bot size={15} className="text-casa-gold" />
                <span className="text-caption text-casa-muted font-semibold uppercase tracking-wide">Today's Briefing</span>
              </div>
              <p className="text-body text-casa-navy leading-relaxed">{briefing.summary_text}</p>
            </div>
          ) : (
            <div className="bg-casa-surface rounded-card border border-casa-border p-5 shadow-card text-center">
              <p className="text-body-sm text-casa-muted">
                No AI summary — <Link to="/settings/ai" className="text-casa-navy underline">add an API key</Link> to enable briefings.
              </p>
            </div>
          )}

          {memberList.length > 0 && (
            <div className="space-y-3">
              <h2 className="font-display text-heading text-casa-navy flex items-center gap-2">
                <CalendarDays size={16} /> Today's Schedules
              </h2>
              {memberList.map(member => (
                <MemberCard key={member.name} member={member} />
              ))}
            </div>
          )}

          {emptyMembers.length > 0 && (
            <div className="flex flex-wrap gap-2">
              {emptyMembers.map(m => (
                <span
                  key={m.name}
                  className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-caption font-medium border border-casa-border text-casa-muted bg-casa-surface"
                >
                  <span className="w-2 h-2 rounded-full" style={{ backgroundColor: m.color_hex }} />
                  {m.name} — free day
                </span>
              ))}
            </div>
          )}

          {memberList.length === 0 && emptyMembers.length === 0 && (
            <div className="bg-casa-surface rounded-card border border-casa-border p-8 text-center shadow-card">
              <p className="text-body text-casa-muted">No events today. Enjoy the quiet! 🌿</p>
            </div>
          )}
        </>
      )}

      <AIAssistantFab
        page="briefing"
        events={todayEvents ?? []}
        family={family ?? []}
        homeCity={weather?.city}
      />
    </div>
  )
}

function MemberCard({ member }: { member: MemberSchedule }) {
  return (
    <div className="bg-casa-surface rounded-card border border-casa-border shadow-card overflow-hidden">
      <div className="flex items-center gap-3 px-4 py-3 border-b border-casa-border">
        <span className="w-7 h-7 rounded-full flex items-center justify-center text-white text-caption font-bold shrink-0" style={{ backgroundColor: member.color_hex }}>
          {member.name[0]}
        </span>
        <span className="font-display text-heading text-casa-navy">{member.name}</span>
        <span className="ml-auto text-caption text-casa-muted">{member.events.length} event{member.events.length !== 1 ? 's' : ''}</span>
      </div>
      <div className="divide-y divide-casa-border">
        {member.events.map((ev, i) => <EventRow key={i} event={ev} />)}
      </div>
    </div>
  )
}

function EventRow({ event }: { event: MemberEvent }) {
  const timeStr = event.all_day
    ? 'All day'
    : format(parseISO(event.start_time), 'h:mm a')

  return (
    <div className="px-4 py-3 flex items-start gap-3">
      <span className="text-caption text-casa-muted w-16 shrink-0 pt-0.5">{timeStr}</span>
      <div className="min-w-0 flex-1">
        <p className="text-body-sm font-medium text-casa-navy leading-snug">{event.title}</p>
        {event.location_name && (
          <p className="text-caption text-casa-muted mt-0.5 truncate">{event.location_name}</p>
        )}
        {event.enrichment?.what_to_bring && event.enrichment.what_to_bring.length > 0 && (
          <p className="text-caption text-casa-gold mt-1">
            Bring: {event.enrichment.what_to_bring.slice(0, 3).join(', ')}
          </p>
        )}
      </div>
    </div>
  )
}
