import { PROFILE_COLOR_OPTIONS } from '../design-system/memberColors'
import type { FamilyMember } from '../types'

export const DEFAULT_CASA_TABOR_MEMBERS: FamilyMember[] = [
  {
    id: 'member-jake',
    name: 'Jake',
    full_name: 'Jacob Tabor',
    role: 'parent',
    color_hex: PROFILE_COLOR_OPTIONS[0].hex,
    color_name: 'Navy',
    phone: '+1 (561) 555-0101',
    email: 'jake@casatabor.com',
    google_calendar_id: null,
    can_drive: true,
    availability_mode: 'flexible',
    show_on_home_sidebar: true,
    is_admin: true,
    avatar_url: null,
    sort_order: 0,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'member-kelly',
    name: 'Kelly',
    full_name: 'Kelly Tabor',
    role: 'parent',
    color_hex: PROFILE_COLOR_OPTIONS[2].hex,
    color_name: 'Forest',
    phone: '+1 (561) 555-0102',
    email: 'kelly@casatabor.com',
    google_calendar_id: null,
    can_drive: true,
    availability_mode: 'strict',
    show_on_home_sidebar: true,
    is_admin: true,
    avatar_url: null,
    sort_order: 1,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'member-olivia',
    name: 'Olivia',
    full_name: 'Olivia Tabor',
    role: 'child',
    color_hex: PROFILE_COLOR_OPTIONS[3].hex,
    color_name: 'Purple',
    phone: null,
    email: null,
    google_calendar_id: null,
    can_drive: false,
    availability_mode: 'strict',
    show_on_home_sidebar: true,
    is_admin: false,
    avatar_url: null,
    sort_order: 2,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'member-owen',
    name: 'Owen',
    full_name: 'Owen Tabor',
    role: 'child',
    color_hex: PROFILE_COLOR_OPTIONS[4].hex,
    color_name: 'Blue',
    phone: null,
    email: null,
    google_calendar_id: null,
    can_drive: false,
    availability_mode: 'strict',
    show_on_home_sidebar: true,
    is_admin: false,
    avatar_url: null,
    sort_order: 3,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'member-emme',
    name: 'Emme',
    full_name: 'Emme Tabor',
    role: 'child',
    color_hex: PROFILE_COLOR_OPTIONS[1].hex,
    color_name: 'Gold',
    phone: null,
    email: null,
    google_calendar_id: null,
    can_drive: false,
    availability_mode: 'strict',
    show_on_home_sidebar: true,
    is_admin: false,
    avatar_url: null,
    sort_order: 4,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'member-giselle',
    name: 'Giselle',
    full_name: 'Giselle (Nanny / Driver)',
    role: 'caregiver',
    color_hex: PROFILE_COLOR_OPTIONS[8].hex,
    color_name: 'Slate',
    phone: '+1 (561) 555-0109',
    email: 'giselle@casatabor.com',
    google_calendar_id: null,
    can_drive: true,
    availability_mode: 'strict',
    show_on_home_sidebar: true,
    is_admin: false,
    avatar_url: null,
    sort_order: 5,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
]
